server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: http://localhost:5000
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    languages:
        - en-US
    pretty_print: true
    limit: 10
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'

logging:
    level: DEBUG

metadata:
    identification:
        title:
            en: pygeoapi default instance
        description:
            en: pygeoapi provides an API to geospatial data
        keywords:
            en:
                - geospatial
                - data
                - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://example.org
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Organization Name
        url: https://pygeoapi.io
    contact:
        name: Silva, Ricardo
        position: Position Title
        address: Mailing Address
        city: City
        stateorprovince: Administrative Area
        postalcode: Zip or Postal Code
        country: Country
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: ricardo.garcia.silva@gmail.com
        url: Contact URL
        hours: Mo-Fr 08:00-17:00
        instructions: During hours of service. Off on weekends.
        role: pointOfContact

resources:
    gimi_1_sentinel:
        type: collection
        title: Sample GIMI file with sentinel data
        description: Sample GIMI file with sentinel data
        keywords:
            - global
        extents:
            spatial:
                bbox: [-0.06638425405434531,51.2789251800994,1.4420952095846158,52.314037793462184]
                # bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        providers:
            - type: coverage
              name: gimirrai.pygeoapi_providers.gimi.GimiCoverageProvider
              data: /home/ubuntu/dev/code-sprint-22-ngiis/GIMI Test Images/gimi_1_sentinel_hevc.heif
              format:
                  name: HEIF
                  mimetype: image/heic

            - type: tile
              name: gimirrai.pygeoapi_providers.gimi.GimiTileProvider
              data: /home/ubuntu/dev/code-sprint-22-ngiis/GIMI Test Images/gimi_1_sentinel_hevc.heif
              options:
                metadata_format: json
                bounds: [-0.06638425405434531,51.2789251800994,1.4420952095846158,52.314037793462184]
                zoom:
                  min: 0
                  max: 11
                schemes:
                    - WebMercatorQuad
                    - WorldCRS84Quad
              format:
                  name: PNG
                  mimetype: image/png
