server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: http://localhost:5000
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    languages:
        - en-US
    pretty_print: true
    limit: 10
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'

logging:
    level: DEBUG

metadata:
    identification:
        title:
            en: pygeoapi default instance
        description:
            en: pygeoapi provides an API to geospatial data
        keywords:
            en:
                - geospatial
                - data
                - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://example.org
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Organization Name
        url: https://pygeoapi.io
    contact:
        name: Silva, Ricardo
        position: Position Title
        address: Mailing Address
        city: City
        stateorprovince: Administrative Area
        postalcode: Zip or Postal Code
        country: Country
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: ricardo.garcia.silva@gmail.com
        url: Contact URL
        hours: Mo-Fr 08:00-17:00
        instructions: During hours of service. Off on weekends.
        role: pointOfContact

resources:
    gimi_1_sentinel:
        type: collection
        title: Sample GIMI file with sentinel data
        description: Sample GIMI file with sentinel data
        keywords:
            - global
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://eccc-msc.github.io/open-data/msc-data/nwp_gdps/readme_gdps_en
              hreflang: en-CA
        providers:
            - type: coverage
              name: rasterio
              data: tests/data/CMC_glb_TMP_TGL_2_latlon.15x.15_2020081000_P000.grib2
              options:
                  DATA_ENCODING: COMPLEX_PACKING
              format:
                  name: GRIB
                  mimetype: application/x-grib2
